version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: |
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT}
          gcloud --quiet config set compute/region ${GOOGLE_COMPUTE_REGION}
      - checkout
      - run: 
          name: Deploy
          command: gcloud beta functions deploy helloWorld --entry-point helloGET --memory 128MB --region ${GOOGLE_COMPUTE_REGION} --trigger-http
workflows:
  version: 2
  master:
    jobs:
      - deploy